-- ============================================================================
-- إشعارات الدائن والمدين — قسم مستقل لمراجعة تصحيحات الفواتير
-- آمن التكرار. يعمل على أي قاعدة قائمة.
-- ============================================================================

create table if not exists public.credit_debit_notes (
  id          bigint generated by default as identity primary key,
  company_id  uuid not null references public.companies(id) on delete cascade,
  number      integer not null,
  note_type   text not null check (note_type in ('credit', 'debit')),
  invoice_id  bigint not null references public.invoices(id),
  customer_id bigint not null references public.customers(id),
  date        date not null,
  amount      numeric(14,2) not null check (amount > 0),
  vat_rate    numeric(5,2) not null default 15,
  reason      text not null default '',
  created_at  timestamptz not null default now(),
  unique (company_id, number)
);

create index if not exists idx_notes_company_customer_date
  on public.credit_debit_notes(company_id, customer_id, date);

create or replace function public.set_note_company_id() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.company_id := public.auth_company_id();
  if new.company_id is null then raise exception 'لا توجد شركة مرتبطة بالحساب.'; end if;
  if not exists(select 1 from public.invoices i where i.id = new.invoice_id and i.company_id = new.company_id and i.customer_id = new.customer_id) then
    raise exception 'الفاتورة والعميل لا ينتميان إلى الشركة الحالية.';
  end if;
  return new;
end $$;

drop trigger if exists trg_note_company on public.credit_debit_notes;
create trigger trg_note_company before insert or update on public.credit_debit_notes
  for each row execute function public.set_note_company_id();

alter table public.credit_debit_notes enable row level security;
drop policy if exists notes_tenant on public.credit_debit_notes;
create policy notes_tenant on public.credit_debit_notes for all
  using (company_id = public.auth_company_id())
  with check (company_id = public.auth_company_id());

grant select, insert on public.credit_debit_notes to authenticated;
grant select, insert, update, delete on public.credit_debit_notes to service_role;

-- ============================================================================
-- بعد التنفيذ: راجع الإشعارات من «العمليات اليومية ← إشعارات مدين/دائن»
-- ============================================================================
