-- ============================================================================
-- v19 — خصومات الموظفين/السائقين (تُقتطع من الرواتب كلياً أو جزئياً)
--
-- تضيف قسم «الخصومات» تحت الرواتب والسلفيات:
--   • جدول employee_deductions   — مستند خصم على موظف (مبلغ + سبب + تاريخ).
--   • جدول deduction_settlements — تسوية الخصم داخل مسير راتب (كلي/جزئي).
--   • عمود deduction_deduction على payrolls — إجمالي خصم الخصومات في المسير.
--   • تحديث save_payroll لقبول تسويات الخصومات والتحقق منها داخل المعاملة.
-- آمن لإعادة التشغيل بالكامل.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- (1) مستندات الخصم على الموظفين
-- ---------------------------------------------------------------------------
create table if not exists public.employee_deductions (
  id          bigint generated by default as identity primary key,
  company_id  uuid not null references public.companies(id) on delete cascade,
  number      integer not null,
  date        date not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  amount      numeric(14,2) not null check (amount > 0),
  reason      text not null default '',
  notes       text not null default '',
  created_at  timestamptz not null default now(),
  unique (company_id, number)
);
create index if not exists idx_employee_deductions_employee_date
  on public.employee_deductions(employee_id, date);
create index if not exists idx_employee_deductions_company_date
  on public.employee_deductions(company_id, date);

-- ---------------------------------------------------------------------------
-- (2) تسويات الخصم داخل مسيرات الرواتب (تُكتب حصراً عبر save_payroll)
-- ---------------------------------------------------------------------------
create table if not exists public.deduction_settlements (
  id                  bigint generated by default as identity primary key,
  company_id          uuid not null references public.companies(id) on delete cascade,
  employee_deduction_id bigint not null references public.employee_deductions(id) on delete cascade,
  payroll_id          bigint not null references public.payrolls(id) on delete cascade,
  amount              double precision not null default 0
);
create index if not exists idx_deduction_settlements_payroll
  on public.deduction_settlements(payroll_id);
create index if not exists idx_deduction_settlements_deduction
  on public.deduction_settlements(employee_deduction_id);

-- ---------------------------------------------------------------------------
-- (3) عمود إجمالي خصم الخصومات على مسير الرواتب
-- ---------------------------------------------------------------------------
alter table public.payrolls
  add column if not exists deduction_deduction double precision not null default 0;

-- ---------------------------------------------------------------------------
-- (4) فرض company_id عند الإدراج + عزل RLS
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['employee_deductions', 'deduction_settlements']
  loop
    execute format('drop trigger if exists trg_set_company_id on public.%I', t);
    execute format(
      'create trigger trg_set_company_id before insert on public.%I
       for each row execute function public.set_company_id()', t);
  end loop;
end $$;

-- حارس السنة المالية المفتوحة على بنود الخصم (مثل باقي الحركات المالية).
-- دالة guard_movement_open_year تُنشأ في ترحيلات سابقة؛ نربطها فقط إن وُجدت.
do $$
begin
  if to_regprocedure('public.guard_movement_open_year()') is not null then
    drop trigger if exists trg_open_year_employee_deductions on public.employee_deductions;
    create trigger trg_open_year_employee_deductions
      before insert or update of date, company_id on public.employee_deductions
      for each row execute function public.guard_movement_open_year();
  end if;
end $$;

alter table public.employee_deductions enable row level security;
drop policy if exists tenant_isolation on public.employee_deductions;
create policy tenant_isolation on public.employee_deductions
  for all to authenticated
  using (company_id = public.auth_company_id() and public.is_company_active())
  with check (company_id = public.auth_company_id() and public.is_company_active());

alter table public.deduction_settlements enable row level security;
drop policy if exists tenant_isolation on public.deduction_settlements;
create policy tenant_isolation on public.deduction_settlements
  for all to authenticated
  using (company_id = public.auth_company_id() and public.is_company_active())
  with check (company_id = public.auth_company_id() and public.is_company_active());

grant select, insert, update, delete on public.employee_deductions to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
-- تسويات الخصم تُنشأ/تُحذف حصراً عبر الدالة الذرية (تتجاوز RLS بصلاحية المُعرِّف).
revoke insert, update, delete on public.deduction_settlements from authenticated, anon;
grant select on public.deduction_settlements to authenticated, service_role;
grant usage, select on sequence public.deduction_settlements_id_seq to service_role;

-- ---------------------------------------------------------------------------
-- (5) تصدير بيانات الشركة يشمل جداول الخصومات الجديدة
-- ---------------------------------------------------------------------------
create or replace function public.export_company_data()
returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_cid uuid := public.auth_company_id();
  v_out jsonb := '{}'::jsonb;
begin
  if v_cid is null then raise exception 'لا توجد شركة مرتبطة بحسابك.'; end if;
  select jsonb_build_object(
    'company', to_jsonb(c),
    'customers', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.customers x where x.company_id = v_cid),
    'employees', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.employees x where x.company_id = v_cid),
    'vehicles', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.vehicles x where x.company_id = v_cid),
    'cashboxes', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.cashboxes x where x.company_id = v_cid),
    'banks', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.banks x where x.company_id = v_cid),
    'financial_years', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.financial_years x where x.company_id = v_cid),
    'invoices', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.invoices x where x.company_id = v_cid),
    'invoice_trips', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.invoice_trips x where x.company_id = v_cid),
    'trip_expenses', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.trip_expenses x where x.company_id = v_cid),
    'receipt_vouchers', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.receipt_vouchers x where x.company_id = v_cid),
    'payment_vouchers', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.payment_vouchers x where x.company_id = v_cid),
    'payrolls', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.payrolls x where x.company_id = v_cid),
    'advance_settlements', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.advance_settlements x where x.company_id = v_cid),
    'employee_deductions', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.employee_deductions x where x.company_id = v_cid),
    'deduction_settlements', (select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) from public.deduction_settlements x where x.company_id = v_cid)
  )
  into v_out
  from public.companies c where c.id = v_cid;
  return v_out;
end $$;
revoke execute on function public.export_company_data() from public, anon;
grant execute on function public.export_company_data() to authenticated;

-- ---------------------------------------------------------------------------
-- (6) حفظ ذرّي لمسير الراتب: تسويات السلف + تسويات الخصومات
-- ---------------------------------------------------------------------------
-- يُسقط الإصدار القديم (توقيع 14 مُعاملاً) لأن توقيع الاستدعاء الاسمي يتغير.
drop function if exists public.save_payroll(bigint, date, bigint, int, int, text, bigint, double precision, double precision, text, double precision, double precision, text, jsonb);

create or replace function public.save_payroll(
  p_payroll_id bigint,
  p_date date,
  p_employee_id bigint,
  p_period_year int,
  p_period_month int,
  p_account_kind text,
  p_account_id bigint,
  p_base_salary double precision,
  p_additions double precision,
  p_additions_note text default '',
  p_advance_deduction double precision default 0,
  p_other_deductions double precision default 0,
  p_notes text default '',
  p_settlements jsonb default '[]'::jsonb,
  p_deduction_settlements jsonb default '[]'::jsonb,
  p_deduction_deduction double precision default null
) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_cid uuid := public.auth_company_id();
  v_payroll_id bigint := p_payroll_id;
  v_number int;
  v_old_date date;
  v_pair jsonb;
  v_vid bigint;
  v_amt double precision;
  v_settled double precision;
  v_src_amount double precision;
  v_total double precision := 0;
  v_ded_total double precision := 0;
  v_deduction_deduction double precision;
  v_net double precision;
begin
  if v_cid is null then raise exception 'لا توجد شركة مرتبطة بحسابك.'; end if;
  if not public.is_company_active() then raise exception 'الوصول غير متاح: اشتراك منتهي أو شركة موقوفة.'; end if;
  if p_employee_id is null then raise exception 'اختر الموظف/السائق.'; end if;
  if not exists (select 1 from public.employees where id = p_employee_id and company_id = v_cid) then
    raise exception 'الموظف المحدد غير موجود.';
  end if;
  if p_account_kind = 'cashbox' then
    if not exists (select 1 from public.cashboxes where id = p_account_id and company_id = v_cid) then
      raise exception 'الخزينة المحددة غير موجودة.';
    end if;
  elsif p_account_kind = 'bank' then
    if not exists (select 1 from public.banks where id = p_account_id and company_id = v_cid) then
      raise exception 'البنك المحدد غير موجود.';
    end if;
  else
    raise exception 'جهة الصرف غير صالحة.';
  end if;
  if p_period_month < 1 or p_period_month > 12 then raise exception 'شهر الراتب يجب أن يكون بين 1 و 12.'; end if;
  if p_period_year < 1900 or p_period_year > 2200 then raise exception 'سنة الراتب غير منطقية.'; end if;
  if p_base_salary <= 0 then raise exception 'الراتب الأساسي يجب أن يكون أكبر من صفر.'; end if;

  -- مطابقة إجمالي خصم السلف لمجموع التسويات الموزعة
  for v_pair in select * from jsonb_array_elements(coalesce(p_settlements, '[]'::jsonb)) loop
    v_total := v_total + coalesce((v_pair->>1)::double precision, 0);
  end loop;
  if abs(v_total - p_advance_deduction) > 0.001 then
    raise exception 'مجموع خصومات السلف الموزعة لا يطابق قيمة الخصم من السلف.';
  end if;

  -- مطابقة إجمالي خصم الخصومات لمجموع تسوياتها (القيمة المحسوبة مصدر الحقيقة)
  for v_pair in select * from jsonb_array_elements(coalesce(p_deduction_settlements, '[]'::jsonb)) loop
    v_ded_total := v_ded_total + coalesce((v_pair->>1)::double precision, 0);
  end loop;
  v_deduction_deduction := round(v_ded_total::numeric, 2);
  if p_deduction_deduction is not null and abs(v_deduction_deduction - p_deduction_deduction) > 0.01 then
    raise exception 'مجموع خصومات الخصومات الموزعة لا يطابق إجمالي خصم الخصومات.';
  end if;

  v_net := round((p_base_salary + p_additions - p_advance_deduction - v_deduction_deduction - p_other_deductions)::numeric, 2);
  if v_net < 0 then raise exception 'صافي الراتب سالب: راجع الإضافات والخصومات.'; end if;

  perform 1 from public.companies where id = v_cid for update;

  if p_payroll_id is null then
    if not exists (select 1 from public.financial_years
                   where company_id = v_cid and status = 'open' and date_from <= p_date and date_to >= p_date) then
      raise exception 'لا يمكن تسجيل حركة بهذا التاريخ: خارج نطاق أي سنة مالية مفتوحة.';
    end if;
    select coalesce(max(number), 0) + 1 into v_number from public.payrolls where company_id = v_cid;
    insert into public.payrolls
      (company_id, number, date, employee_id, period_year, period_month, account_kind, account_id,
       base_salary, additions, additions_note, advance_deduction, other_deductions,
       deduction_deduction, net_salary, notes)
    values
      (v_cid, v_number, p_date, p_employee_id, p_period_year, p_period_month, p_account_kind, p_account_id,
       p_base_salary, p_additions, p_additions_note, p_advance_deduction, p_other_deductions,
       v_deduction_deduction, v_net, p_notes)
    returning id into v_payroll_id;
  else
    select date into v_old_date from public.payrolls where id = p_payroll_id and company_id = v_cid for update;
    if v_old_date is null then raise exception 'الراتب غير موجود.'; end if;
    if not exists (select 1 from public.financial_years
                   where company_id = v_cid and status = 'open' and date_from <= v_old_date and date_to >= v_old_date) then
      raise exception 'لا يمكن تعديل حركة بتاريخ قديم خارج السنة المالية المفتوحة.';
    end if;
    if not exists (select 1 from public.financial_years
                   where company_id = v_cid and status = 'open' and date_from <= p_date and date_to >= p_date) then
      raise exception 'لا يمكن تسجيل حركة بهذا التاريخ: خارج نطاق أي سنة مالية مفتوحة.';
    end if;
    update public.payrolls set
      date = p_date, employee_id = p_employee_id, period_year = p_period_year, period_month = p_period_month,
      account_kind = p_account_kind, account_id = p_account_id, base_salary = p_base_salary,
      additions = p_additions, additions_note = p_additions_note, advance_deduction = p_advance_deduction,
      other_deductions = p_other_deductions, deduction_deduction = v_deduction_deduction,
      net_salary = v_net, notes = p_notes
    where id = v_payroll_id;
    -- تُحذف التسويات القديمة وتُعاد من الصورة الجديدة (cascade يغطي الحذف اليدوي أيضاً)
    delete from public.advance_settlements where payroll_id = v_payroll_id;
    delete from public.deduction_settlements where payroll_id = v_payroll_id;
  end if;

  -- تسويات السلف
  for v_pair in select * from jsonb_array_elements(coalesce(p_settlements, '[]'::jsonb)) loop
    v_vid := (v_pair->>0)::bigint;
    v_amt := coalesce((v_pair->>1)::double precision, 0);
    if v_amt <= 0 then continue; end if;
    if not exists (select 1 from public.payment_vouchers
                   where id = v_vid and voucher_type = 'advance'
                     and employee_id = p_employee_id and company_id = v_cid) then
      raise exception 'سلفة غير موجودة أو لا تخص هذا الموظف.';
    end if;
    select amount into v_src_amount from public.payment_vouchers where id = v_vid;
    select coalesce(sum(amount), 0) into v_settled from public.advance_settlements where payment_voucher_id = v_vid;
    if v_amt > (v_src_amount - v_settled) + 0.001 then
      raise exception 'قيمة الخصم من إحدى السلف أكبر من المتبقي منها.';
    end if;
    insert into public.advance_settlements (company_id, payment_voucher_id, payroll_id, amount)
    values (v_cid, v_vid, v_payroll_id, v_amt);
  end loop;

  -- تسويات الخصومات (كلي / جزئي)
  for v_pair in select * from jsonb_array_elements(coalesce(p_deduction_settlements, '[]'::jsonb)) loop
    v_vid := (v_pair->>0)::bigint;
    v_amt := coalesce((v_pair->>1)::double precision, 0);
    if v_amt <= 0 then continue; end if;
    if not exists (select 1 from public.employee_deductions
                   where id = v_vid and employee_id = p_employee_id and company_id = v_cid) then
      raise exception 'خصم غير موجود أو لا يخص هذا الموظف.';
    end if;
    select amount into v_src_amount from public.employee_deductions where id = v_vid;
    select coalesce(sum(amount), 0) into v_settled from public.deduction_settlements where employee_deduction_id = v_vid;
    if v_amt > (v_src_amount - v_settled) + 0.001 then
      raise exception 'قيمة الخصم من إحدى بنود الخصومات أكبر من المتبقي منها.';
    end if;
    insert into public.deduction_settlements (company_id, employee_deduction_id, payroll_id, amount)
    values (v_cid, v_vid, v_payroll_id, v_amt);
  end loop;

  perform public.log_activity('payroll.save', 'payroll', v_payroll_id::text, '');
  return v_payroll_id;
end $$;

revoke execute on function public.save_payroll(bigint, date, bigint, int, int, text, bigint, double precision, double precision, text, double precision, double precision, text, jsonb, jsonb, double precision) from public, anon;
grant execute on function public.save_payroll(bigint, date, bigint, int, int, text, bigint, double precision, double precision, text, double precision, double precision, text, jsonb, jsonb, double precision) to authenticated, service_role;
