-- ============================================================================
-- ترقية قاعدة بيانات قائمة (عزل user_id) إلى عزل company_id + اشتراك واحد
-- الصق هذا الملف كاملاً في Supabase Dashboard > SQL Editor > Run (آمن التكرار)
--
-- ينقل البيانات الحالية: يُنشئ شركة لكل ملف شخصي قائم ويحوّل user_id ← company_id
-- ============================================================================

-- 1) جداول الشركات والملفات الجديدة
create table if not exists public.companies (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  phone              text default '',
  email              text default '',
  address            text default '',
  currency           text default 'ر.س',
  vat_rate           double precision not null default 15,
  vat_note           text default 'فاتورة مرجعية — ضريبة القيمة المضافة 15%',
  plan_type          text not null default 'open' check (plan_type in ('monthly', 'yearly', 'open')),
  subscription_start date default current_date,
  subscription_end   date,
  is_active          boolean not null default true,
  created_at         timestamptz default now()
);

-- profiles القديمة لا تحتوي company_id؛ إضافته هنا يجعل الترحيلة قابلة
-- للتشغيل سواءً كانت قاعدة البيانات على النسخة الأحادية أو على نسخة جزئية.
alter table public.profiles add column if not exists company_id uuid references public.companies(id) on delete cascade;

create table if not exists public.activity_logs (
  id          bigint generated by default as identity primary key,
  actor_id    uuid references auth.users(id) on delete set null,
  actor_email text default '',
  action      text not null,
  entity      text default '',
  entity_id   text default '',
  detail      text default '',
  created_at  timestamptz default now()
);

-- 2) إضافة company_id لكل جداول البيانات
do $$
declare
  t text;
begin
  foreach t in array array[
    'financial_years','customers','employees','vehicles','cashboxes','banks',
    'invoices','invoice_trips','trip_expenses','receipt_vouchers',
    'payment_vouchers','payrolls','advance_settlements','year_snapshots'
  ]
  loop
    execute format(
      'alter table public.%I add column if not exists company_id uuid references public.companies(id) on delete cascade', t);
  end loop;
end $$;

-- 3) تحويل الملفات الشخصية: إنشاء شركة لكل ملف وربطها
do $$
declare
  r record;
  v_company uuid;
begin
  for r in select * from public.profiles loop
    -- هذه الترحيلة يجب أن تكون قابلة لإعادة التشغيل. إنشاء شركة جديدة في كل
    -- تشغيل كان يغيّر profiles.company_id ويجعل السجلات القديمة تبدو مفقودة.
    if r.company_id is not null then
      continue;
    end if;
    insert into public.companies (name, phone, email)
    values (
      coalesce(
        nullif(btrim(to_jsonb(r)->>'company_name'), ''),
        nullif(btrim(to_jsonb(r)->>'name'), ''),
        nullif(to_jsonb(r)->>'email', ''), 'شركة'
      ),
      coalesce(to_jsonb(r)->>'phone', ''), to_jsonb(r)->>'email'
    )
    returning id into v_company;
    update public.profiles set company_id = v_company where id = r.id;
  end loop;
end $$;

-- 4) نقل user_id ← company_id في بقية الجداول (عبر الربط بالملف الشخصي)
do $$
declare
  t text;
begin
  foreach t in array array[
    'financial_years','customers','employees','vehicles','cashboxes','banks',
    'invoices','invoice_trips','trip_expenses','receipt_vouchers',
    'payment_vouchers','payrolls','advance_settlements','year_snapshots'
  ]
  loop
    execute format(
      'update public.%I d set company_id = p.company_id
       from public.profiles p where p.id = d.user_id and d.company_id is null', t);
  end loop;
end $$;

-- 5) نقل الإعدادات (settings) إلى عمود الشركة
do $$
declare
  r record;
begin
  for r in select * from public.settings loop
    update public.companies c
    set name = coalesce(r.value, c.name)
    from public.profiles p
    where p.id = r.user_id and p.company_id = c.id and r.key = 'company_name';
  end loop;
end $$;

-- 6) أعمدة الاشتراك والملفات الجديدة
alter table public.profiles drop column if exists role;
alter table public.profiles drop column if exists is_active;
alter table public.profiles drop column if exists company_name;
alter table public.profiles drop column if exists phone;

-- 7) حارس company_id + RLS + دوال الإدارة (كما في schema.sql)
create or replace function public.is_admin() returns boolean
language sql stable set search_path = public, pg_temp as $$
  select coalesce((auth.jwt() ->> 'email'), '') = 'conta.moha@gmail.com';
$$;

create or replace function public.auth_company_id() returns uuid
language sql stable security definer set search_path = public as $$
  select p.company_id from public.profiles p where p.id = auth.uid();
$$;

create or replace function public.is_company_active() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select c.is_active and (c.subscription_end is null or c.subscription_end >= current_date)
     from public.companies c join public.profiles p on p.company_id = c.id
     where p.id = auth.uid()),
    false
  );
$$;

create or replace function public.set_company_id() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  new.company_id := public.auth_company_id();
  return new;
end $$;

do $$
declare
  t text;
begin
  foreach t in array array[
    'financial_years','customers','employees','vehicles','cashboxes','banks',
    'invoices','invoice_trips','trip_expenses','receipt_vouchers',
    'payment_vouchers','payrolls','advance_settlements','year_snapshots'
  ]
  loop
    execute format('drop trigger if exists trg_set_company_id on public.%I', t);
    execute format(
      'create trigger trg_set_company_id before insert on public.%I
       for each row execute function public.set_company_id()', t);
  end loop;
end $$;

-- RLS
alter table public.profiles enable row level security;
drop policy if exists profiles_own on public.profiles;
drop policy if exists profiles_admin on public.profiles;
create policy profiles_own_select on public.profiles for select using (id = auth.uid());
create policy profiles_own_insert on public.profiles for insert
  with check (id = auth.uid() and company_id is null);
create policy profiles_own_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_admin on public.profiles for all using (public.is_admin()) with check (public.is_admin());

alter table public.companies enable row level security;
drop policy if exists companies_own on public.companies;
create policy companies_own on public.companies
  for select using (id = public.auth_company_id() or public.is_admin());
create policy companies_own_update on public.companies
  for update using (id = public.auth_company_id()) with check (id = public.auth_company_id());
create policy companies_admin on public.companies for all
  using (public.is_admin()) with check (public.is_admin());

alter table public.activity_logs enable row level security;
drop policy if exists activity_read on public.activity_logs;
create policy activity_read on public.activity_logs for select
  using (actor_id = auth.uid() or public.is_admin());

do $$
declare
  t text;
begin
  foreach t in array array[
    'financial_years','customers','employees','vehicles','cashboxes','banks',
    'invoices','invoice_trips','trip_expenses','receipt_vouchers',
    'payment_vouchers','payrolls','advance_settlements','year_snapshots'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists tenant_isolation on public.%I', t);
    execute format('drop policy if exists admin_full_access on public.%I', t);
    execute format(
      'create policy tenant_isolation on public.%I for all
         using (company_id = public.auth_company_id() and public.is_company_active())
         with check (company_id = public.auth_company_id() and public.is_company_active())', t);
    -- (أُزيلت) admin_full_access — كانت تُجمع بـ OR مع tenant_isolation فتُظهر
    -- بيانات كل الشركات في حساب المطوّر. انظر migration_admin_privacy_v5.sql.
    execute format('drop policy if exists admin_full_access on public.%I', t);
  end loop;
end $$;

-- دوال التسجيل والإدارة
create or replace function public.register_company(
  p_company_name text, p_name text default '', p_phone text default ''
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_user  uuid := auth.uid();
  v_email text := coalesce(auth.jwt() ->> 'email', '');
  v_company uuid;
begin
  if v_user is null then raise exception 'يجب تسجيل الدخول أولاً.'; end if;
  if p_company_name is null or btrim(p_company_name) = '' then raise exception 'اسم الشركة مطلوب.'; end if;
  select company_id into v_company from public.profiles where id = v_user;
  if v_company is not null then return v_company; end if;
  insert into public.companies (name, phone, email) values (btrim(p_company_name), p_phone, v_email)
  returning id into v_company;
  insert into public.profiles (id, company_id, email, name) values (v_user, v_company, v_email, p_name);
  perform public.log_activity('signup', 'company', v_company::text, p_company_name);
  return v_company;
end $$;

create or replace function public.admin_set_company_status(p_company_id uuid, p_active boolean) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  update public.companies set is_active = p_active where id = p_company_id;
  perform public.log_activity(
    case when p_active then 'admin.activate_company' else 'admin.deactivate_company' end,
    'company', p_company_id::text, '');
end $$;

create or replace function public.admin_set_subscription(
  p_company_id uuid, p_plan_type text, p_end_date date default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  if p_plan_type not in ('monthly', 'yearly', 'open') then raise exception 'نوع الاشتراك غير صالح.'; end if;
  update public.companies
  set plan_type = p_plan_type,
      subscription_end = case when p_plan_type = 'open' then null else p_end_date end
  where id = p_company_id;
  perform public.log_activity('admin.set_subscription', 'company', p_company_id::text,
    p_plan_type || coalesce(' | ' || p_end_date::text, ''));
end $$;

create or replace function public.admin_delete_company(p_company_id uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  delete from public.companies where id = p_company_id;
  perform public.log_activity('admin.delete_company', 'company', p_company_id::text, '');
end $$;

revoke execute on function public.register_company(text, text, text) from public, anon;
grant execute on function public.register_company(text, text, text) to authenticated;
revoke execute on function public.admin_set_company_status(uuid, boolean) from public, anon;
revoke execute on function public.admin_set_subscription(uuid, text, date) from public, anon;
revoke execute on function public.admin_delete_company(uuid) from public, anon;
grant execute on function public.admin_set_company_status(uuid, boolean) to authenticated, service_role;
grant execute on function public.admin_set_subscription(uuid, text, date) to authenticated, service_role;
grant execute on function public.admin_delete_company(uuid) to authenticated, service_role;

-- أقل امتياز
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
revoke update on public.profiles from authenticated;
grant update (name) on public.profiles to authenticated;
revoke update on public.companies from authenticated;
grant update (name, phone, email, address, currency, vat_rate, vat_note) on public.companies to authenticated;
