/* ============================================================================
   ترحيل شامل وآمن لتعديلات جلسة Arena
   شغّل هذا الملف كاملاً مرة واحدة في Supabase SQL Editor.

   خصائص الأمان:
   - آمن عند إعادة التشغيل: يستخدم IF NOT EXISTS / CREATE OR REPLACE / DROP POLICY.
   - لا يحذف أي بيانات ولا يعدّل الحركات القديمة.
   - يعيد إصلاح ربط البيانات القديمة عبر user_id إن كان العمود موجوداً.
   - كل الجداول الجديدة معزولة بـ company_id وRLS.
   - يأخذ snapshot للأرصدة ثم ينشئ سنة جديدة مع أرصدة افتتاحية مستقلة.
   ============================================================================ */

begin;

/* 1) إكمال ربط profiles بالشركة */
alter table if exists public.profiles
  add column if not exists company_id uuid references public.companies(id) on delete cascade;

/* 2) إصلاح بيانات الترحيل القديم دون حذف أو دمج شركات تلقائياً */
do $$
declare t text;
begin
  foreach t in array array[
    'financial_years','customers','employees','vehicles','cashboxes','banks',
    'invoices','invoice_trips','trip_expenses','receipt_vouchers',
    'payment_vouchers','payrolls','advance_settlements','year_snapshots'
  ] loop
    if to_regclass('public.' || t) is not null
       and exists (select 1 from information_schema.columns where table_schema='public' and table_name=t and column_name='user_id') then
      execute format('update public.%I d set company_id=p.company_id from public.profiles p where d.user_id=p.id and p.company_id is not null and d.company_id is distinct from p.company_id', t);
    end if;
  end loop;
end $$;

/* 3) توحيد القيم الافتراضية القديمة فقط؛ الإعدادات الجديدة تبقى قابلة للتعديل */
update public.companies set currency='ر.س' where currency in ('ج.م','EGP','جنيه مصري');
update public.companies set vat_rate=15 where vat_rate is null or vat_rate=14;

/* 4) إشعارات الدائن والمدين */
create table if not exists public.credit_debit_notes (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  number integer not null,
  note_type text not null check (note_type in ('credit','debit')),
  invoice_id bigint not null references public.invoices(id),
  customer_id bigint not null references public.customers(id),
  date date not null,
  amount numeric(14,2) not null check (amount > 0),
  vat_rate numeric(5,2) not null default 15,
  reason text not null default '',
  created_at timestamptz not null default now(),
  unique(company_id, number)
);
create index if not exists idx_notes_company_customer_date on public.credit_debit_notes(company_id, customer_id, date);

create or replace function public.set_note_company_id() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  new.company_id := public.auth_company_id();
  if new.company_id is null then raise exception 'لا توجد شركة مرتبطة بالحساب.'; end if;
  if not exists(select 1 from public.invoices i where i.id=new.invoice_id and i.company_id=new.company_id and i.customer_id=new.customer_id) then
    raise exception 'الفاتورة والعميل لا ينتميان إلى الشركة الحالية.';
  end if;
  return new;
end $$;
drop trigger if exists trg_note_company on public.credit_debit_notes;
create trigger trg_note_company before insert or update on public.credit_debit_notes for each row execute function public.set_note_company_id();
alter table public.credit_debit_notes enable row level security;
drop policy if exists notes_tenant on public.credit_debit_notes;
create policy notes_tenant on public.credit_debit_notes for all
  using (company_id=public.auth_company_id()) with check (company_id=public.auth_company_id());

/* 5) جدول أرصدة افتتاحية مستقل لكل سنة */
create table if not exists public.year_opening_balances (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  year_id bigint not null references public.financial_years(id) on delete cascade,
  entity_type text not null check (entity_type in ('customer','cashbox','bank','supplier')),
  entity_id bigint not null,
  balance numeric(14,2) not null default 0,
  unique(company_id, year_id, entity_type, entity_id)
);
create index if not exists idx_year_opening_company_year on public.year_opening_balances(company_id,year_id);
alter table public.year_opening_balances enable row level security;
drop policy if exists year_opening_tenant on public.year_opening_balances;
create policy year_opening_tenant on public.year_opening_balances for all
  using (company_id=public.auth_company_id()) with check (company_id=public.auth_company_id());

/* 6) إنشاء السنة التالية وترحيل الرصيد الختامي إلى سجل افتتاحي مستقل */
create or replace function public.create_next_financial_year(
  p_closed_year_id bigint, p_year integer, p_date_from date, p_date_to date
) returns bigint language plpgsql security definer set search_path=public as $$
declare
  v_cid uuid := public.auth_company_id(); v_new bigint; r record;
begin
  if v_cid is null then raise exception 'لا توجد شركة مرتبطة بالحساب.'; end if;
  if not exists(select 1 from public.financial_years where id=p_closed_year_id and company_id=v_cid and status='closed') then
    raise exception 'يجب إغلاق السنة السابقة أولاً.';
  end if;
  if p_year <= 0 or p_date_from > p_date_to then raise exception 'بيانات السنة الجديدة غير صحيحة.'; end if;
  if exists(select 1 from public.financial_years where company_id=v_cid and year=p_year) then raise exception 'السنة الجديدة موجودة مسبقاً.'; end if;
  insert into public.financial_years(company_id,year,date_from,date_to,status,notes)
    values(v_cid,p_year,p_date_from,p_date_to,'open','تم الترحيل من السنة السابقة') returning id into v_new;

  for r in select c.id, c.opening_balance +
      coalesce((select sum((coalesce((select sum(t.price) from public.invoice_trips t where t.invoice_id=i.id and t.company_id=v_cid),0)+coalesce((select sum(e.amount) from public.trip_expenses e join public.invoice_trips et on et.id=e.trip_id where et.invoice_id=i.id and e.source='customer' and e.company_id=v_cid),0))*(1+i.vat_rate/100)) from public.invoices i where i.customer_id=c.id and i.company_id=v_cid),0)-
      coalesce((select sum(amount) from public.receipt_vouchers where customer_id=c.id and company_id=v_cid and voucher_type='customer'),0) balance
    from public.customers c where c.company_id=v_cid loop
    insert into public.year_opening_balances(company_id,year_id,entity_type,entity_id,balance) values(v_cid,v_new,'customer',r.id,r.balance);
  end loop;

  for r in select c.id, c.opening_balance + coalesce((select sum(amount) from public.receipt_vouchers where account_kind='cashbox' and account_id=c.id and company_id=v_cid),0)-coalesce((select sum(amount) from public.payment_vouchers where account_kind='cashbox' and account_id=c.id and company_id=v_cid),0)-coalesce((select sum(net_salary) from public.payrolls where account_kind='cashbox' and account_id=c.id and company_id=v_cid),0) balance from public.cashboxes c where c.company_id=v_cid loop
    insert into public.year_opening_balances(company_id,year_id,entity_type,entity_id,balance) values(v_cid,v_new,'cashbox',r.id,r.balance);
  end loop;

  for r in select b.id, b.opening_balance + coalesce((select sum(amount) from public.receipt_vouchers where account_kind='bank' and account_id=b.id and company_id=v_cid),0)-coalesce((select sum(amount) from public.payment_vouchers where account_kind='bank' and account_id=b.id and company_id=v_cid),0)-coalesce((select sum(net_salary) from public.payrolls where account_kind='bank' and account_id=b.id and company_id=v_cid),0) balance from public.banks b where b.company_id=v_cid loop
    insert into public.year_opening_balances(company_id,year_id,entity_type,entity_id,balance) values(v_cid,v_new,'bank',r.id,r.balance);
  end loop;
  return v_new;
end $$;
revoke execute on function public.create_next_financial_year(bigint,integer,date,date) from public,anon;
grant execute on function public.create_next_financial_year(bigint,integer,date,date) to authenticated,service_role;

/* 7) تصحيح اعتماد الاشتراك: مدفوع يتقدم على التجربة، والتجديد يحسب من النهاية الحالية */
create or replace function public.admin_review_activation_request(
  p_request_id uuid, p_approve boolean, p_admin_notes text default ''
) returns void language plpgsql security definer set search_path=public as $$
declare v_req public.activation_requests%rowtype; v_from date;
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  select * into v_req from public.activation_requests where id=p_request_id for update;
  if not found then raise exception 'الطلب غير موجود.'; end if;
  if v_req.status <> 'pending' then raise exception 'تمت مراجعة هذا الطلب مسبقاً.'; end if;
  if p_approve then
    select greatest(coalesce(subscription_end,current_date),current_date) into v_from from public.companies where id=v_req.company_id;
    update public.activation_requests set status='approved', admin_notes=left(coalesce(p_admin_notes,''),500), reviewed_at=now() where id=p_request_id;
    update public.companies set plan_type=v_req.plan_type, subscription_start=current_date,
      subscription_end=v_from+(case when v_req.plan_type='yearly' then 365 else 30 end), trial_end=current_date-1 where id=v_req.company_id;
  else
    update public.activation_requests set status='rejected', admin_notes=left(coalesce(p_admin_notes,''),500), reviewed_at=now() where id=p_request_id;
  end if;
end $$;
revoke execute on function public.admin_review_activation_request(uuid,boolean,text) from public,anon;
grant execute on function public.admin_review_activation_request(uuid,boolean,text) to authenticated,service_role;

commit;

/* تحقق اختياري بعد التنفيذ:
select name,currency,vat_rate,plan_type,trial_end,subscription_end from public.companies;
select * from public.year_opening_balances order by year_id,entity_type,entity_id;
*/
