-- ============================================================================
-- v7 — دورة الموردين الكاملة (آمن التكرار)
--
--   مورّد ← فاتورة مشتريات بالضريبة ← سند دفع للمورّد ← رصيد وكشف حساب وأعمار ديون
--   كل الجداول معزولة بـ company_id + RLS، ولا وصول للمطوّر عليها (سياسة v5).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) الموردون (بنفس الحزمة الضريبية والعنوان الوطني)
-- ---------------------------------------------------------------------------
create table if not exists public.suppliers (
  id               bigint generated by default as identity primary key,
  company_id       uuid not null references public.companies(id) on delete cascade,
  code             text not null default '',
  name             text not null,
  name_en          text default '',
  phone            text default '',
  email            text default '',
  contact_person   text default '',
  address          text default '',
  opening_balance  double precision not null default 0,   -- موجب = علينا للمورّد
  notes            text default '',
  -- ضريبي
  tax_number       text default '',
  commercial_reg   text default '',
  entity_type      text default 'company',
  tax_status       text default 'taxable',
  -- عنوان وطني
  country          text default 'SA',
  region           text default '',
  city             text default '',
  district         text default '',
  street           text default '',
  building_no      text default '',
  postal_code      text default '',
  additional_no    text default '',
  payment_terms    int not null default 0,
  created_at       timestamptz default now()
);
create index if not exists idx_suppliers_company on public.suppliers(company_id, name);

alter table public.suppliers drop constraint if exists suppliers_entity_type_check;
alter table public.suppliers add constraint suppliers_entity_type_check
  check (entity_type in ('establishment', 'company', 'individual', 'nonprofit', 'government'));
alter table public.suppliers drop constraint if exists suppliers_tax_status_check;
alter table public.suppliers add constraint suppliers_tax_status_check
  check (tax_status in ('taxable', 'exempt', 'not_registered'));

drop trigger if exists trg_check_tax_suppliers on public.suppliers;
create trigger trg_check_tax_suppliers before insert or update on public.suppliers
  for each row execute function public.check_tax_identifiers();

-- ---------------------------------------------------------------------------
-- 2) فواتير المشتريات (رأس + بنود) مع ضريبة القيمة المضافة
-- ---------------------------------------------------------------------------
create table if not exists public.purchase_invoices (
  id            bigint generated by default as identity primary key,
  company_id    uuid not null references public.companies(id) on delete cascade,
  number        integer not null,
  date          date not null,
  supplier_id   bigint not null references public.suppliers(id),
  supplier_ref  text default '',                     -- رقم فاتورة المورّد
  vat_rate      double precision not null default 15,
  vat_included  boolean not null default false,      -- هل الأسعار شاملة الضريبة؟
  notes         text default '',
  created_at    timestamptz default now()
);
create index if not exists idx_pinv_company on public.purchase_invoices(company_id, date);
create index if not exists idx_pinv_supplier on public.purchase_invoices(supplier_id);

create table if not exists public.purchase_items (
  id          bigint generated by default as identity primary key,
  company_id  uuid not null references public.companies(id) on delete cascade,
  invoice_id  bigint not null references public.purchase_invoices(id) on delete cascade,
  item_name   text not null default '',
  unit        text default '',
  qty         double precision not null default 1,
  unit_price  double precision not null default 0,
  /** نسبة ضريبة البند (تسمح ببنود معفاة داخل نفس الفاتورة) */
  vat_rate    double precision not null default 15,
  notes       text default '',
  created_at  timestamptz default now()
);
create index if not exists idx_pitems_invoice on public.purchase_items(invoice_id);

-- ---------------------------------------------------------------------------
-- 3) سندات الدفع: ربطها بالمورّد
-- ---------------------------------------------------------------------------
alter table public.payment_vouchers add column if not exists supplier_id bigint
  references public.suppliers(id) on delete set null;
alter table public.payment_vouchers add column if not exists purchase_invoice_id bigint
  references public.purchase_invoices(id) on delete set null;

alter table public.payment_vouchers drop constraint if exists payment_vouchers_voucher_type_check;
alter table public.payment_vouchers add constraint payment_vouchers_voucher_type_check
  check (voucher_type in ('trip', 'advance', 'vehicle', 'general', 'supplier'));

-- ---------------------------------------------------------------------------
-- 4) العزل والصلاحيات
-- ---------------------------------------------------------------------------
do $iso$
declare t text;
begin
  foreach t in array array['suppliers', 'purchase_invoices', 'purchase_items'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists tenant_isolation on public.%I', t);
    execute format(
      'create policy tenant_isolation on public.%I for all
         using (company_id = public.auth_company_id())
         with check (company_id = public.auth_company_id())', t);
    execute format('drop trigger if exists trg_set_company_id on public.%I', t);
    execute format(
      'create trigger trg_set_company_id before insert on public.%I
         for each row execute function public.set_company_id()', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('revoke all on public.%I from anon', t);
  end loop;
end $iso$;

-- ---------------------------------------------------------------------------
-- 5) حفظ ذرّي لفاتورة المشتريات (رأس + بنود في معاملة واحدة)
-- ---------------------------------------------------------------------------
create or replace function public.save_purchase_invoice(
  p_invoice_id bigint,          -- null = فاتورة جديدة
  p_date date,
  p_supplier_id bigint,
  p_supplier_ref text,
  p_vat_rate double precision,
  p_vat_included boolean,
  p_notes text,
  p_items jsonb                 -- [{item_name, unit, qty, unit_price, vat_rate, notes}]
) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_cid uuid := public.auth_company_id();
  v_id  bigint := p_invoice_id;
  v_num integer;
  it    jsonb;
begin
  if v_cid is null then raise exception 'جلسة غير صالحة.'; end if;
  if p_supplier_id is null then raise exception 'اختر المورّد.'; end if;
  if not exists (select 1 from public.suppliers s where s.id = p_supplier_id and s.company_id = v_cid) then
    raise exception 'المورّد غير موجود.';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'أضف بنداً واحداً على الأقل للفاتورة.';
  end if;

  if v_id is null then
    select coalesce(max(number), 0) + 1 into v_num
      from public.purchase_invoices where company_id = v_cid;
    insert into public.purchase_invoices
      (company_id, number, date, supplier_id, supplier_ref, vat_rate, vat_included, notes)
    values
      (v_cid, v_num, p_date, p_supplier_id, public.safe_text(p_supplier_ref, 60),
       coalesce(p_vat_rate, 15), coalesce(p_vat_included, false), public.safe_text(p_notes, 500))
    returning id into v_id;
  else
    update public.purchase_invoices
       set date = p_date,
           supplier_id = p_supplier_id,
           supplier_ref = public.safe_text(p_supplier_ref, 60),
           vat_rate = coalesce(p_vat_rate, 15),
           vat_included = coalesce(p_vat_included, false),
           notes = public.safe_text(p_notes, 500)
     where id = v_id and company_id = v_cid;
    if not found then raise exception 'الفاتورة غير موجودة.'; end if;
    delete from public.purchase_items where invoice_id = v_id and company_id = v_cid;
  end if;

  for it in select * from jsonb_array_elements(p_items) loop
    if coalesce((it ->> 'qty')::double precision, 0) <= 0 then
      raise exception 'الكمية يجب أن تكون أكبر من صفر.';
    end if;
    if coalesce((it ->> 'unit_price')::double precision, 0) < 0 then
      raise exception 'سعر الوحدة لا يمكن أن يكون سالباً.';
    end if;
    insert into public.purchase_items
      (company_id, invoice_id, item_name, unit, qty, unit_price, vat_rate, notes)
    values (
      v_cid, v_id,
      public.safe_text(it ->> 'item_name', 160),
      public.safe_text(it ->> 'unit', 20),
      (it ->> 'qty')::double precision,
      (it ->> 'unit_price')::double precision,
      coalesce((it ->> 'vat_rate')::double precision, coalesce(p_vat_rate, 15)),
      public.safe_text(it ->> 'notes', 200)
    );
  end loop;

  return v_id;
end $$;

grant execute on function public.save_purchase_invoice(
  bigint, date, bigint, text, double precision, boolean, text, jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- 6) منع حذف مورّد له حركات
-- ---------------------------------------------------------------------------
create or replace function public.guard_supplier_delete() returns trigger
language plpgsql as $$
declare n_inv int; n_pay int;
begin
  select count(*) into n_inv from public.purchase_invoices where supplier_id = old.id;
  select count(*) into n_pay from public.payment_vouchers where supplier_id = old.id;
  if n_inv > 0 or n_pay > 0 then
    raise exception 'لا يمكن حذف المورّد لوجود حركات مرتبطة به (% فاتورة، % سند دفع).', n_inv, n_pay;
  end if;
  return old;
end $$;

drop trigger if exists trg_guard_supplier_delete on public.suppliers;
create trigger trg_guard_supplier_delete before delete on public.suppliers
  for each row execute function public.guard_supplier_delete();

-- ============================================================================
-- للتأكد:
--   select * from public.rls_audit();  -- يجب أن تعود فارغة
-- ============================================================================
