-- ============================================================================
-- v16 — إشعار دائن لمرتجع نقلة محددة من فاتورة العميل
--
-- يربط الإشعار بالنقلات المختارة، ويحتسب قيمته وضريبته خادمياً داخل معاملة
-- واحدة، ويمنع إرجاع النقلة نفسها مرتين. آمن لإعادة التشغيل.
-- ============================================================================

create table if not exists public.credit_note_trips (
  id             bigint generated by default as identity primary key,
  company_id     uuid not null references public.companies(id) on delete cascade,
  credit_note_id bigint not null references public.credit_debit_notes(id) on delete cascade,
  trip_id        bigint not null references public.invoice_trips(id),
  amount         numeric(14,2) not null check (amount > 0),
  created_at     timestamptz not null default now()
);

create unique index if not exists uq_credit_note_trips_note_trip
  on public.credit_note_trips(credit_note_id, trip_id);
create unique index if not exists uq_credit_note_trips_one_return_per_trip
  on public.credit_note_trips(company_id, trip_id);
create index if not exists idx_credit_note_trips_note
  on public.credit_note_trips(credit_note_id);

alter table public.credit_note_trips enable row level security;
drop policy if exists credit_note_trips_tenant_select on public.credit_note_trips;
create policy credit_note_trips_tenant_select on public.credit_note_trips
  for select to authenticated
  using (
    company_id = public.auth_company_id()
    and public.is_company_active()
  );

-- الإنشاء حصراً عبر RPC الذرية أدناه؛ لا يقبل مبلغاً أو ضريبة من المتصفح.
create or replace function public.save_credit_note_for_trips_v16(
  p_invoice_id bigint,
  p_date date,
  p_reason text,
  p_trip_ids bigint[]
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_company_id uuid := public.auth_company_id();
  v_customer_id bigint;
  v_invoice_date date;
  v_vat_rate numeric(5,2);
  v_reason text;
  v_requested_count integer;
  v_trip_count integer;
  v_amount numeric(14,2);
  v_number integer;
  v_note_id bigint;
begin
  if v_company_id is null then
    raise exception 'لا توجد شركة مرتبطة بحسابك.';
  end if;
  if not public.is_company_active() then
    raise exception 'الوصول غير متاح: اشتراك منتهي أو شركة موقوفة.';
  end if;
  if p_invoice_id is null then
    raise exception 'الفاتورة غير صالحة.';
  end if;
  if p_date is null then
    raise exception 'تاريخ الإشعار مطلوب.';
  end if;
  if p_trip_ids is null or cardinality(p_trip_ids) = 0 then
    raise exception 'اختر نقلة واحدة على الأقل لإصدار الإشعار الدائن.';
  end if;

  select count(distinct selected_id)
    into v_requested_count
    from unnest(p_trip_ids) as selected(selected_id);
  if v_requested_count <> cardinality(p_trip_ids) then
    raise exception 'قائمة النقلات المختارة تحتوي على تكرار.';
  end if;

  v_reason := public.safe_text(p_reason, 4000);
  if v_reason = '' then
    raise exception 'سبب الإشعار إلزامي للمراجعة المحاسبية.';
  end if;

  -- قفل الشركة يمنع سباق رقم الإشعار أو إرجاع النقلة نفسها من تبويبين.
  perform 1 from public.companies where id = v_company_id for update;

  select i.customer_id, i.date, round(i.vat_rate::numeric, 2)
    into v_customer_id, v_invoice_date, v_vat_rate
    from public.invoices i
   where i.id = p_invoice_id
     and i.company_id = v_company_id;
  if not found then
    raise exception 'الفاتورة المرتبطة غير موجودة.';
  end if;
  if p_date < v_invoice_date then
    raise exception 'تاريخ الإشعار لا يجوز أن يسبق تاريخ الفاتورة.';
  end if;
  if not exists (
    select 1
      from public.financial_years y
     where y.company_id = v_company_id
       and y.status = 'open'
       and p_date between y.date_from and y.date_to
  ) then
    raise exception 'لا يمكن تسجيل حركة بهذا التاريخ: خارج نطاق أي سنة مالية مفتوحة.';
  end if;

  select count(*), round(coalesce(sum(t.price), 0)::numeric, 2)
    into v_trip_count, v_amount
    from public.invoice_trips t
   where t.company_id = v_company_id
     and t.invoice_id = p_invoice_id
     and t.id = any(p_trip_ids);
  if v_trip_count <> v_requested_count then
    raise exception 'إحدى النقلات المختارة غير موجودة أو لا تنتمي إلى هذه الفاتورة.';
  end if;
  if v_amount <= 0 then
    raise exception 'إجمالي النقلات المختارة يجب أن يكون أكبر من صفر.';
  end if;

  if exists (
    select 1
      from public.credit_note_trips returned
     where returned.company_id = v_company_id
       and returned.trip_id = any(p_trip_ids)
  ) then
    raise exception 'تم إصدار إشعار دائن مسبقاً لإحدى النقلات المختارة.';
  end if;

  select coalesce(max(n.number), 0) + 1
    into v_number
    from public.credit_debit_notes n
   where n.company_id = v_company_id;

  insert into public.credit_debit_notes
    (company_id, number, note_type, invoice_id, customer_id, date, amount, vat_rate, reason)
  values
    (v_company_id, v_number, 'credit', p_invoice_id, v_customer_id, p_date, v_amount, v_vat_rate, v_reason)
  returning id into v_note_id;

  insert into public.credit_note_trips
    (company_id, credit_note_id, trip_id, amount)
  select v_company_id, v_note_id, t.id, round(t.price::numeric, 2)
    from public.invoice_trips t
   where t.company_id = v_company_id
     and t.invoice_id = p_invoice_id
     and t.id = any(p_trip_ids);

  perform public.log_activity(
    'credit_note.trip_return', 'credit_debit_note', v_note_id::text,
    'invoice=' || p_invoice_id::text || '; trips=' || array_to_string(p_trip_ids, ',')
  );
  return v_note_id;
end
$$;

revoke all on function public.save_credit_note_for_trips_v16(bigint, date, text, bigint[])
  from public, anon;
grant execute on function public.save_credit_note_for_trips_v16(bigint, date, text, bigint[])
  to authenticated, service_role;

-- أقل امتياز: المستخدم يقرأ الارتباطات، والحفظ يتم فقط عبر الدالة الذرية.
grant select on public.credit_note_trips to authenticated, service_role;
grant insert, update, delete on public.credit_note_trips to service_role;
-- الجدول يُنشئ sequence بعد منح الصلاحيات العامة في بعض قواعد الترقية.
grant usage, select on sequence public.credit_note_trips_id_seq to service_role;
revoke insert, update, delete on public.credit_note_trips from authenticated, anon;
