-- إقفال وترحيل السنة + إشعارات الدائن والمدين
begin;

create table if not exists public.credit_debit_notes (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  number integer not null,
  note_type text not null check (note_type in ('credit','debit')),
  invoice_id bigint not null references public.invoices(id),
  customer_id bigint not null references public.customers(id),
  date date not null,
  amount numeric(14,2) not null check (amount > 0),
  vat_rate numeric(5,2) not null default 15,
  reason text not null default '',
  created_at timestamptz not null default now(),
  unique(company_id, number)
);
create index if not exists idx_notes_customer_date on public.credit_debit_notes(company_id, customer_id, date);

create table if not exists public.year_opening_balances (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  year_id bigint not null references public.financial_years(id) on delete cascade,
  entity_type text not null check (entity_type in ('customer','cashbox','bank','supplier')),
  entity_id bigint not null,
  balance numeric(14,2) not null default 0,
  unique(company_id, year_id, entity_type, entity_id)
);

alter table public.credit_debit_notes enable row level security;
drop policy if exists notes_tenant on public.credit_debit_notes;
create policy notes_tenant on public.credit_debit_notes for all using (company_id = public.auth_company_id()) with check (company_id = public.auth_company_id());
alter table public.year_opening_balances enable row level security;
drop policy if exists year_opening_tenant on public.year_opening_balances;
create policy year_opening_tenant on public.year_opening_balances for all using (company_id = public.auth_company_id()) with check (company_id = public.auth_company_id());

create or replace function public.create_next_financial_year(p_closed_year_id bigint, p_year integer, p_date_from date, p_date_to date)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  v_cid uuid := public.auth_company_id(); v_new bigint; r record;
begin
  if v_cid is null then raise exception 'لا توجد شركة مرتبطة بالحساب.'; end if;
  if not exists(select 1 from financial_years where id=p_closed_year_id and company_id=v_cid and status='closed') then raise exception 'يجب إغلاق السنة السابقة أولاً.'; end if;
  if p_date_from > p_date_to or p_year <= 0 then raise exception 'بيانات السنة الجديدة غير صحيحة.'; end if;
  if exists(select 1 from financial_years where company_id=v_cid and year=p_year) then raise exception 'السنة الجديدة موجودة مسبقاً.'; end if;
  insert into financial_years(company_id,year,date_from,date_to,status,notes) values(v_cid,p_year,p_date_from,p_date_to,'open','تم الترحيل من السنة السابقة') returning id into v_new;
  -- الأرصدة تحفظ كسجل افتتاحي مستقل؛ لا نعدل opening_balance الأصلي ولا نكرر الحركات.
  for r in select id, 'customer' entity_type, balance from (
    select c.id,
      c.opening_balance
      + coalesce((select sum((coalesce((select sum(t.price) from invoice_trips t where t.invoice_id=inv.id and t.company_id=v_cid),0)
          + coalesce((select sum(e.amount) from trip_expenses e join invoice_trips et on et.id=e.trip_id
              where et.invoice_id=inv.id and e.source='customer' and e.company_id=v_cid),0)) * (1+inv.vat_rate/100))
        from invoices inv where inv.customer_id=c.id and inv.company_id=v_cid),0)
      - coalesce((select sum(amount) from receipt_vouchers where customer_id=c.id and company_id=v_cid and voucher_type='customer'),0) balance
    from customers c where c.company_id=v_cid
  ) x loop
    insert into year_opening_balances(company_id,year_id,entity_type,entity_id,balance) values(v_cid,v_new,r.entity_type,r.id,r.balance);
  end loop;
  for r in select id, 'cashbox' entity_type, opening_balance +
      coalesce((select sum(amount) from receipt_vouchers where account_kind='cashbox' and account_id=c.id and company_id=v_cid),0) -
      coalesce((select sum(amount) from payment_vouchers where account_kind='cashbox' and account_id=c.id and company_id=v_cid),0) -
      coalesce((select sum(net_salary) from payrolls where account_kind='cashbox' and account_id=c.id and company_id=v_cid),0) balance
      from cashboxes c where c.company_id=v_cid loop
    insert into year_opening_balances(company_id,year_id,entity_type,entity_id,balance) values(v_cid,v_new,r.entity_type,r.id,r.balance);
  end loop;
  for r in select id, 'bank' entity_type, opening_balance +
      coalesce((select sum(amount) from receipt_vouchers where account_kind='bank' and account_id=b.id and company_id=v_cid),0) -
      coalesce((select sum(amount) from payment_vouchers where account_kind='bank' and account_id=b.id and company_id=v_cid),0) -
      coalesce((select sum(net_salary) from payrolls where account_kind='bank' and account_id=b.id and company_id=v_cid),0) balance
      from banks b where b.company_id=v_cid loop
    insert into year_opening_balances(company_id,year_id,entity_type,entity_id,balance) values(v_cid,v_new,r.entity_type,r.id,r.balance);
  end loop;
  return v_new;
end $$;
revoke execute on function public.create_next_financial_year(bigint,integer,date,date) from public,anon;
grant execute on function public.create_next_financial_year(bigint,integer,date,date) to authenticated,service_role;
commit;
