-- ============================================================================
-- v26 — الأصناف والخدمات (النقلات كخدمات بلا مخزون فعلي)
--
--   • جدول public.items: كتالوج أصناف/خدمات لكل شركة. النوع 'service' (خدمة)
--     لا يحمل مخزوناً فعلياً ولا يتحرك له رصيد كميات — البيانات المعروضة في
--     تقارير الخدمات محسوبة من الاستخدام الفعلي في نقلات الفواتير.
--   • عمود public.invoice_trips.item_id: ربط كل نقلة بالخدمة الخاصة بها.
--   • تعبئة تلقائية: خدمة افتراضية «خدمة نقل» لكل شركة، وربط النقلات القديمة
--     بها حتى لا تختفي بيانات سابقة من التقارير.
--   • إعادة تعريف public.save_invoice بنفس توقيعها الحالي (لا يتغير أي استدعاء)
--     لتقرأ item_id وتتحقق أن الخدمة تخص شركة المستخدم.
--   • تحديث فحص صحة قاعدة البيانات ودالة إعادة ضبط بيانات الشركة ليشملا items.
--
-- آمن التكرار: يمكن تنفيذه أكثر من مرة دون أثر مزدوج.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) جدول الأصناف والخدمات
-- ---------------------------------------------------------------------------
create table if not exists public.items (
  id            bigint generated by default as identity primary key,
  company_id    uuid not null references public.companies(id) on delete cascade,
  code          text not null default '',
  name          text not null default '',
  name_en       text default '',
  -- service = خدمة (بلا مخزون فعلي) | product = صنف مخزني (للتصنيف والتقارير فقط)
  item_type     text not null default 'service'
                check (item_type in ('service', 'product')),
  unit          text default '',
  default_price double precision not null default 0 check (default_price >= 0),
  description   text default '',
  is_active     boolean not null default true,
  notes         text default '',
  -- خط الخدمة (اختياري): خدمة تمثل خط سير «من ← إلى» مثل «نقل الرياض ← الدمام».
  -- عند اختيارها في النقلة يُعبَّأ المسار منها ويُقفل، وتبقى الخدمات العامة بلا خط.
  from_loc      text not null default '',
  to_loc        text not null default '',
  created_at    timestamptz default now()
);
create index if not exists idx_items_route on public.items(company_id, from_loc, to_loc);

create unique index if not exists uq_items_company_name
  on public.items(company_id, lower(name));
create unique index if not exists uq_items_company_code
  on public.items(company_id, code) where code <> '';
create index if not exists idx_items_company_type
  on public.items(company_id, item_type, is_active);

-- إضافة عمودَي الخط لقاعدة قائمة (آمن التكرار)
alter table public.items add column if not exists from_loc text not null default '';
alter table public.items add column if not exists to_loc   text not null default '';
create index if not exists idx_items_route on public.items(company_id, from_loc, to_loc);

comment on table public.items is
  'كتالوج الأصناف والخدمات. الخدمات (item_type = service) لا تحمل مخزوناً فعلياً؛ تُستخدم تربطاً في نقلات الفواتير وتُبنى منها تقارير الخدمات.';

-- ---------------------------------------------------------------------------
-- 2) ربط النقلات بالخدمة
--    (on delete set null حتى لا يفقد حذف خدمة سابقة أي نقلة، والحذف الفعلي
--     للخدمة المستخدمة ممنوع من طبقة التطبيق مع اقتراح التعطيل بدلاً منه)
-- ---------------------------------------------------------------------------
alter table public.invoice_trips add column if not exists item_id bigint
  references public.items(id) on delete set null;
create index if not exists idx_trips_item on public.invoice_trips(item_id);

-- ---------------------------------------------------------------------------
-- 3) خدمة افتراضية لكل شركة + ربط النقلات القديمة
--    (لا تُنشأ إن كانت الشركة تملك أصنافاً بالفعل حتى لا تُضاف خدمة زائدة)
-- ---------------------------------------------------------------------------
insert into public.items (company_id, code, name, item_type, unit, description)
select c.id, 'ITM-0001', 'خدمة نقل', 'service', 'نقلة',
       'خدمة نقل عامة أُنشئت تلقائياً لربط النقلات السابقة'
  from public.companies c
 where not exists (select 1 from public.items i where i.company_id = c.id);

update public.invoice_trips t
   set item_id = (
     select i.id from public.items i
      where i.company_id = t.company_id
      order by (i.item_type = 'service') desc, i.id
      limit 1
   )
 where t.item_id is null;

-- ---------------------------------------------------------------------------
-- 4) العزل والصلاحيات (نفس نمط جداول الشركة)
-- ---------------------------------------------------------------------------
alter table public.items enable row level security;

do $iso$
begin
  drop policy if exists tenant_isolation on public.items;
  create policy tenant_isolation on public.items for all
    using (company_id = public.auth_company_id() and public.is_company_active())
    with check (company_id = public.auth_company_id() and public.is_company_active());

  drop trigger if exists trg_set_company_id on public.items;
  create trigger trg_set_company_id before insert on public.items
    for each row execute function public.set_company_id();

  grant select, insert, update, delete on public.items to authenticated, service_role;
  revoke all on public.items from anon;
end $iso$;

grant usage, select on sequence public.items_id_seq to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5) دالة إدراج خدمة جديدة بترقيم آمن (تمنع تكرار الاسم داخل الشركة)
--    تُستخدم من الواجهة عند الإنشاء السريع من شاشة الفاتورة.
-- ---------------------------------------------------------------------------
drop function if exists public.save_item_v26(bigint, text, text, text, double precision, text, text);
create or replace function public.save_item_v26(
  p_item_id bigint,
  p_name text,
  p_item_type text default 'service',
  p_unit text default '',
  p_default_price double precision default 0,
  p_description text default '',
  p_notes text default '',
  p_from_loc text default '',
  p_to_loc text default ''
) returns bigint
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_cid uuid := public.auth_company_id();
  v_id bigint := p_item_id;
  v_name text := btrim(coalesce(p_name, ''));
  v_type text := coalesce(nullif(btrim(p_item_type), ''), 'service');
  v_from text := btrim(coalesce(p_from_loc, ''));
  v_to   text := btrim(coalesce(p_to_loc, ''));
  v_code text;
  v_seq bigint;
begin
  if v_cid is null then raise exception 'لا توجد شركة مرتبطة بحسابك.'; end if;
  if not public.is_company_active() then raise exception 'الوصول غير متاح: اشتراك منتهي أو شركة موقوفة.'; end if;
  if v_name = '' then raise exception 'يجب إدخال اسم الصنف/الخدمة.'; end if;
  if char_length(v_name) > 160 then raise exception 'اسم الصنف/الخدمة أطول من الحد المسموح.'; end if;
  if v_type not in ('service', 'product') then raise exception 'نوع الصنف غير صالح.'; end if;
  if coalesce(p_default_price, 0) < 0 then raise exception 'السعر الافتراضي لا يمكن أن يكون سالباً.'; end if;
  if coalesce(p_default_price, 0) > 999999999999 then raise exception 'السعر الافتراضي خارج النطاق المسموح.'; end if;
  if char_length(btrim(coalesce(p_unit, ''))) > 40 then raise exception 'وحدة الصنف أطول من الحد المسموح (40 حرفاً).'; end if;
  if char_length(btrim(coalesce(p_description, ''))) > 1000 then raise exception 'وصف الصنف أطول من الحد المسموح (1000 حرف).'; end if;
  if char_length(btrim(coalesce(p_notes, ''))) > 1000 then raise exception 'ملاحظات الصنف أطول من الحد المسموح (1000 حرف).'; end if;
  if char_length(v_from) > 200 or char_length(v_to) > 200 then
    raise exception 'مكان الانطلاق أو الوصول للخط أطول من الحد المسموح (200 حرف).';
  end if;
  -- إما خدمة خط كامل (من ووصول) أو خدمة عامة بلا خط — لا أنصاف خطوط
  if (v_from = '') <> (v_to = '') then
    raise exception 'أكمل مكان الانطلاق والوصول للخط، أو اتركهما فارغين لخدمة عامة بلا خط.';
  end if;
  if exists (
    select 1 from public.items
     where company_id = v_cid and lower(name) = lower(v_name) and (v_id is null or id <> v_id)
  ) then
    raise exception 'يوجد صنف/خدمة بنفس الاسم.';
  end if;

  perform 1 from public.companies where id = v_cid for update;

  if v_id is null then
    insert into public.items (company_id, code, name, item_type, unit, default_price, description, notes, from_loc, to_loc)
    values (v_cid, '', v_name, v_type, btrim(coalesce(p_unit, '')),
            round(coalesce(p_default_price, 0)::numeric, 2)::double precision,
            btrim(coalesce(p_description, '')), btrim(coalesce(p_notes, '')), v_from, v_to)
    returning id into v_id;
    -- ترقيم الصنف: أكبر رقم مستخدم + 1 (فلا يُعاد استخدام كود صف محذوف)،
    -- مع حلقة تأكيد احتياطية تمنع أي تصادم على فهرس uq_items_company_code.
    select coalesce(max(nullif(regexp_replace(code, '\D', '', 'g'), '')::bigint), 0) + 1
      into v_seq
      from public.items
     where company_id = v_cid and code ~ '^ITM-[0-9]+$';
    loop
      v_code := 'ITM-' || lpad(v_seq::text, 4, '0');
      exit when not exists (
        select 1 from public.items where company_id = v_cid and code = v_code
      );
      v_seq := v_seq + 1;
    end loop;
    update public.items set code = v_code where id = v_id and company_id = v_cid;
  else
    update public.items set
      name = v_name,
      item_type = v_type,
      unit = btrim(coalesce(p_unit, '')),
      default_price = round(coalesce(p_default_price, 0)::numeric, 2)::double precision,
      description = btrim(coalesce(p_description, '')),
      notes = btrim(coalesce(p_notes, '')),
      from_loc = v_from,
      to_loc = v_to
    where id = v_id and company_id = v_cid;
    if not found then raise exception 'الصنف/الخدمة غير موجود.'; end if;
  end if;

  perform public.log_activity('item.save', 'item', v_id::text, '');
  return v_id;
end $$;

revoke all on function public.save_item_v26(bigint, text, text, text, double precision, text, text, text, text) from public, anon;
grant execute on function public.save_item_v26(bigint, text, text, text, double precision, text, text, text, text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6) إعادة تعريف save_invoice — نفس التوقيع تماماً، مع قراءة item_id
--    المنطق مطابق للنسخة النهائية في schema.sql (حاويات + مصادر تمويل) مع
--    إضافة التحقق من الخدمة وربطها بكل نقلة.
-- ---------------------------------------------------------------------------
create or replace function public.save_invoice(
  p_invoice_id  bigint, p_date date, p_customer_id bigint, p_vat_rate double precision,
  p_notes text default '', p_attachments jsonb default '[]'::jsonb, p_trips jsonb default '[]'::jsonb,
  p_container_number text default ''
) returns bigint
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_cid uuid := public.auth_company_id(); v_invoice_id bigint := p_invoice_id;
  v_number int; v_old_date date; v_trip jsonb; v_trip_id bigint;
  v_kept bigint[] := '{}'::bigint[]; v_linked int; v_exp jsonb;
  v_qty int; v_unit double precision; v_line double precision;
  v_item bigint; v_item_from text; v_item_to text;
  v_from text; v_to text;
  v_containers jsonb; v_container jsonb; v_container_text text;
  v_normalized_containers jsonb; v_seen_containers text[] := '{}'::text[];
  v_eqty double precision; v_eunit double precision; v_eamount double precision;
  v_source text; v_kind text; v_acc bigint; v_exp_id bigint; v_pnum int;
begin
  if v_cid is null then raise exception 'لا توجد شركة مرتبطة بحسابك.'; end if;
  if not public.is_company_active() then raise exception 'الوصول غير متاح: اشتراك منتهي أو شركة موقوفة.'; end if;
  if p_customer_id is null then raise exception 'اختر العميل.'; end if;
  if jsonb_array_length(p_trips) = 0 then raise exception 'أضف نقلة واحدة على الأقل للفاتورة.'; end if;
  perform 1 from public.companies where id = v_cid for update;
  if not exists (select 1 from public.customers where id = p_customer_id and company_id = v_cid) then
    raise exception 'العميل المحدد غير موجود.';
  end if;

  if p_invoice_id is null then
    if not exists (select 1 from public.financial_years where company_id = v_cid and status = 'open' and date_from <= p_date and date_to >= p_date) then
      raise exception 'لا يمكن تسجيل حركة بهذا التاريخ: خارج نطاق أي سنة مالية مفتوحة.';
    end if;
    select coalesce(max(number), 0) + 1 into v_number from public.invoices where company_id = v_cid;
    insert into public.invoices (company_id, number, date, customer_id, vat_rate, notes, attachments, container_number)
    values (v_cid, v_number, p_date, p_customer_id, p_vat_rate, p_notes, p_attachments, coalesce(p_container_number, ''))
    returning id into v_invoice_id;
  else
    select date into v_old_date from public.invoices where id = p_invoice_id and company_id = v_cid for update;
    if v_old_date is null then raise exception 'الفاتورة غير موجودة.'; end if;
    if not exists (select 1 from public.financial_years where company_id = v_cid and status = 'open' and date_from <= v_old_date and date_to >= v_old_date) then
      raise exception 'لا يمكن تعديل حركة بتاريخ قديم خارج السنة المالية المفتوحة.';
    end if;
    if not exists (select 1 from public.financial_years where company_id = v_cid and status = 'open' and date_from <= p_date and date_to >= p_date) then
      raise exception 'لا يمكن تسجيل حركة بهذا التاريخ: خارج نطاق أي سنة مالية مفتوحة.';
    end if;
    update public.invoices set date = p_date, customer_id = p_customer_id, vat_rate = p_vat_rate, notes = p_notes, attachments = p_attachments,
      container_number = coalesce(p_container_number, '')
    where id = v_invoice_id;
  end if;

  for v_trip in select * from jsonb_array_elements(p_trips) loop
    if (v_trip->>'id') is not null then v_kept := array_append(v_kept, (v_trip->>'id')::bigint); end if;
  end loop;

  -- حذف النقلات المُزالة: تُمنع فقط إن كانت مرتبطة بسندات دفع يدوية
  for v_trip_id in select id from public.invoice_trips where invoice_id = v_invoice_id and not (id = any(v_kept)) loop
    select count(*) into v_linked from public.payment_vouchers
     where voucher_type = 'trip' and trip_id = v_trip_id and source_expense_id is null;
    if v_linked > 0 then raise exception 'لا يمكن حذف نقلة مرتبطة بسندات دفع يدوية. احذف السندات المرتبطة أولاً.'; end if;
    delete from public.payment_vouchers where trip_id = v_trip_id and source_expense_id is not null;
    delete from public.invoice_trips where id = v_trip_id;
  end loop;

  for v_trip in select * from jsonb_array_elements(p_trips) loop
    v_qty  := greatest(coalesce((v_trip->>'qty')::int, 1), 1);
    v_unit := coalesce((v_trip->>'unit_price')::double precision, 0);
    if v_unit <= 0 then v_unit := coalesce((v_trip->>'price')::double precision, 0) / v_qty; end if;
    v_line := round((v_qty * v_unit)::numeric, 2)::double precision;
    if v_line <= 0 then raise exception 'سعر النقلة يجب أن يكون أكبر من صفر.'; end if;

    -- الخدمة إلزامية لكل نقلة، ويجب أن تكون من أصناف نفس الشركة (v26)
    v_item := nullif(v_trip->>'item_id', '')::bigint;
    if v_item is null then raise exception 'اختر الصنف/الخدمة لكل نقلة.'; end if;
    if not exists (select 1 from public.items where id = v_item and company_id = v_cid) then
      raise exception 'الصنف/الخدمة المحدد غير موجود.';
    end if;

    -- الصنف هو المصدر الوحيد للمسار: صنف الخدمة المخزَّن بخط (من ← إلى) يفرض
    -- مساره على النقلة مهما أرسل العميل، والخدمة العامة بلا خط تترك المسار يدوياً.
    select from_loc, to_loc into v_item_from, v_item_to
      from public.items where id = v_item and company_id = v_cid;
    if coalesce(v_item_from, '') <> '' or coalesce(v_item_to, '') <> '' then
      v_from := v_item_from;
      v_to := v_item_to;
    else
      v_from := btrim(coalesce(v_trip->>'from_loc', ''));
      v_to   := btrim(coalesce(v_trip->>'to_loc', ''));
    end if;
    if v_from = '' or v_to = '' then
      raise exception 'أكمل أماكن الانطلاق والوصول لكل نقلة.';
    end if;

    v_containers := coalesce(v_trip->'container_numbers', '[]'::jsonb);
    if jsonb_typeof(v_containers) <> 'array' then raise exception 'أرقام الحاويات يجب أن تكون قائمة.'; end if;
    if jsonb_array_length(v_containers) > v_qty then
      raise exception 'عدد أرقام الحاويات لا يجوز أن يتجاوز عدد النقلات (%).', v_qty;
    end if;
    v_normalized_containers := '[]'::jsonb;
    for v_container in select value from jsonb_array_elements(v_containers) loop
      if jsonb_typeof(v_container) <> 'string' then raise exception 'رقم الحاوية يجب أن يكون نصاً.'; end if;
      v_container_text := btrim(v_container #>> '{}');
      if v_container_text = '' then raise exception 'رقم الحاوية لا يمكن أن يكون فارغاً.'; end if;
      if char_length(v_container_text) > 100 then raise exception 'رقم الحاوية أطول من الحد المسموح (100 حرف).'; end if;
      if upper(v_container_text) = any(v_seen_containers) then
        raise exception 'رقم الحاوية «%» مكرر داخل الفاتورة.', v_container_text;
      end if;
      v_seen_containers := array_append(v_seen_containers, upper(v_container_text));
      v_normalized_containers := v_normalized_containers || jsonb_build_array(v_container_text);
    end loop;

    if (v_trip->>'id') is not null then
      v_trip_id := (v_trip->>'id')::bigint;
      update public.invoice_trips set
        vehicle_id = nullif(v_trip->>'vehicle_id', '')::bigint,
        driver_id  = nullif(v_trip->>'driver_id', '')::bigint,
        item_id    = v_item,
        from_loc   = v_from,
        to_loc     = v_to,
        qty        = v_qty,
        unit_price        = v_unit,
        price             = v_line,
        container_numbers = v_normalized_containers,
        notes              = coalesce(v_trip->>'notes', '')
      where id = v_trip_id and invoice_id = v_invoice_id;
      if not found then raise exception 'النقلة غير موجودة ضمن هذه الفاتورة.'; end if;
      delete from public.trip_expenses where trip_id = v_trip_id;
    else
      insert into public.invoice_trips
        (company_id, invoice_id, vehicle_id, driver_id, item_id, from_loc, to_loc, qty, unit_price, price, container_numbers, notes)
      values (v_cid, v_invoice_id, nullif(v_trip->>'vehicle_id', '')::bigint, nullif(v_trip->>'driver_id', '')::bigint,
              v_item, v_from, v_to, v_qty, v_unit, v_line,
              v_normalized_containers, coalesce(v_trip->>'notes', ''))
      returning id into v_trip_id;
    end if;

    for v_exp in select * from jsonb_array_elements(coalesce(v_trip->'expenses', '[]'::jsonb)) loop
      v_eqty  := greatest(coalesce((v_exp->>'qty')::double precision, 1), 0.0001);
      v_eunit := coalesce((v_exp->>'unit_amount')::double precision, 0);
      if v_eunit <= 0 then v_eunit := coalesce((v_exp->>'amount')::double precision, 0) / v_eqty; end if;
      v_eamount := round((v_eqty * v_eunit)::numeric, 2)::double precision;
      if v_eamount <= 0 then raise exception 'مبلغ مصروف النقلة يجب أن يكون أكبر من صفر.'; end if;

      v_source := coalesce(v_exp->>'source', 'cash');
      if v_source not in ('cash', 'driver', 'supplier', 'customer') then
        raise exception 'مصدر تمويل المصروف غير صالح.';
      end if;

      v_kind := nullif(v_exp->>'account_kind', '');
      v_acc  := nullif(v_exp->>'account_id', '')::bigint;

      if v_source = 'cash' then
        if v_kind is null or v_acc is null then
          raise exception 'اختر الخزينة أو البنك الذي صُرف منه المصروف النقدي.';
        end if;
        if v_kind = 'cashbox' then
          if not exists (select 1 from public.cashboxes where id = v_acc and company_id = v_cid) then
            raise exception 'الخزينة المحددة غير موجودة.'; end if;
        elsif v_kind = 'bank' then
          if not exists (select 1 from public.banks where id = v_acc and company_id = v_cid) then
            raise exception 'البنك المحدد غير موجود.'; end if;
        else
          raise exception 'نوع الحساب غير صالح.';
        end if;
      end if;

      if v_source = 'driver' and nullif(v_trip->>'driver_id', '') is null then
        raise exception 'حدّد السائق في النقلة قبل تسجيل مصروف من عهدته.';
      end if;

      insert into public.trip_expenses
        (company_id, trip_id, expense_type, qty, unit_amount, amount, source, account_kind, account_id, supplier_name, notes)
      values
        (v_cid, v_trip_id, coalesce(v_exp->>'expense_type', 'other'), v_eqty, v_eunit, v_eamount, v_source,
         case when v_source = 'cash' then v_kind else null end,
         case when v_source = 'cash' then v_acc else null end,
         coalesce(v_exp->>'supplier_name', ''), coalesce(v_exp->>'notes', ''))
      returning id into v_exp_id;

      if v_source = 'cash' then
        select coalesce(max(number), 0) + 1 into v_pnum from public.payment_vouchers where company_id = v_cid;
        insert into public.payment_vouchers
          (company_id, number, date, account_kind, account_id, voucher_type, trip_id, employee_id, vehicle_id,
           amount, description, source_expense_id)
        values
          (v_cid, v_pnum, p_date, v_kind, v_acc, 'trip', v_trip_id,
           nullif(v_trip->>'driver_id', '')::bigint, nullif(v_trip->>'vehicle_id', '')::bigint,
           v_eamount,
           'مصروف نقلة (تلقائي): ' || coalesce(v_exp->>'notes', coalesce(v_exp->>'expense_type', '')),
           v_exp_id);
      end if;
    end loop;
  end loop;

  perform public.log_activity('invoice.save', 'invoice', v_invoice_id::text, '');
  return v_invoice_id;
end $$;

revoke execute on function public.save_invoice(bigint, date, bigint, double precision, text, jsonb, jsonb, text) from public, anon;
grant execute on function public.save_invoice(bigint, date, bigint, double precision, text, jsonb, jsonb, text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7) تحديث فحص صحة قاعدة البيانات ليشمل جدول items
-- ---------------------------------------------------------------------------
create or replace function public.admin_database_health_v18()
returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_expected_tables text[] := array[
    'companies','profiles','feature_catalog','company_features','activity_logs',
    'financial_years','customers','employees','vehicles','cashboxes','banks',
    'invoices','invoice_trips','trip_expenses','receipt_vouchers','payment_vouchers',
    'credit_debit_notes','credit_note_trips','payrolls','advance_settlements','deduction_settlements','employee_deductions','year_snapshots',
    'activation_requests','suppliers','purchase_invoices','purchase_items','items','year_opening_balances',
    'support_messages','complaints','complaint_messages','app_settings','site_visitors'
  ];
  v_expected_functions text[] := array[
    'auth_company_id','is_company_active','register_company_with_year','save_invoice',
    'save_payroll','admin_set_company_feature','admin_get_company_extras_v18',
    'admin_reset_company_data_v18','admin_platform_stats_v18','record_site_visit_v18',
    'save_item_v26'
  ];
  v_tables jsonb; v_functions jsonb; v_healthy boolean;
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'name', expected.name,
      'exists', c.oid is not null,
      'rls_enabled', coalesce(c.relrowsecurity, false),
      'policy_count', (select count(*) from pg_policies p where p.schemaname = 'public' and p.tablename = expected.name)
    ) order by expected.name), '[]'::jsonb),
    coalesce(bool_and(c.oid is not null and c.relrowsecurity), false)
    into v_tables, v_healthy
    from unnest(v_expected_tables) expected(name)
    left join pg_namespace n on n.nspname = 'public'
    left join pg_class c on c.relnamespace = n.oid and c.relname = expected.name and c.relkind = 'r';

  select coalesce(jsonb_agg(jsonb_build_object(
      'name', expected.name,
      'exists', case
        when expected.name = 'save_invoice' then
          to_regprocedure('public.save_invoice(bigint,date,bigint,double precision,text,jsonb,jsonb,text)') is not null
        else exists(
          select 1 from pg_proc p
          join pg_namespace ns on ns.oid = p.pronamespace
          where ns.nspname = 'public' and p.proname = expected.name
        )
      end
    ) order by expected.name), '[]'::jsonb)
    into v_functions
    from unnest(v_expected_functions) expected(name);

  if exists(
    select 1 from unnest(v_expected_functions) f(name)
     where case
       when f.name = 'save_invoice' then
         to_regprocedure('public.save_invoice(bigint,date,bigint,double precision,text,jsonb,jsonb,text)') is null
       else not exists(
         select 1 from pg_proc p
         join pg_namespace ns on ns.oid = p.pronamespace
         where ns.nspname = 'public' and p.proname = f.name
       )
     end
  ) then v_healthy := false; end if;

  return jsonb_build_object(
    'healthy', v_healthy,
    'checked_at', now(),
    'database_time', clock_timestamp(),
    'postgres_version', current_setting('server_version'),
    'tables', v_tables,
    'functions', v_functions
  );
end $$;

revoke all on function public.admin_database_health_v18() from public, anon;
grant execute on function public.admin_database_health_v18() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 8) إعادة ضبط بيانات الشركة تشمل الأصناف/الخدمات أيضاً
-- ---------------------------------------------------------------------------
create or replace function public.admin_reset_company_data_v18(p_company_id uuid)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_table text; v_count bigint; v_total bigint := 0;
  v_counts jsonb := '{}'::jsonb; v_year_id bigint; v_year int;
  v_tables text[] := array[
    'credit_note_trips', 'credit_debit_notes', 'advance_settlements', 'deduction_settlements',
    'employee_deductions',
    'purchase_items', 'payment_vouchers', 'receipt_vouchers', 'payrolls',
    'trip_expenses', 'invoice_trips', 'invoices',
    'purchase_invoices', 'suppliers', 'items',
    'year_opening_balances', 'year_snapshots', 'financial_years',
    'vehicles', 'employees', 'cashboxes', 'banks', 'customers'
  ];
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  if p_company_id is null or not exists(select 1 from public.companies where id = p_company_id) then
    raise exception 'الشركة غير موجودة.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('reset-company:' || p_company_id::text, 0));

  foreach v_table in array v_tables loop
    if to_regclass('public.' || v_table) is not null then
      execute format('delete from public.%I where company_id = $1', v_table) using p_company_id;
      get diagnostics v_count = row_count;
      v_total := v_total + v_count;
      v_counts := v_counts || jsonb_build_object(v_table, v_count);
    end if;
  end loop;

  v_year := extract(year from current_date)::int;
  insert into public.financial_years(company_id, year, date_from, date_to, status, notes)
  values(
    p_company_id, v_year, make_date(v_year, 1, 1), make_date(v_year, 12, 31),
    'open', 'سنة جديدة أُنشئت تلقائياً بعد إعادة ضبط بيانات الشركة'
  ) returning id into v_year_id;

  perform public.log_activity(
    'admin.reset_company_data', 'company', p_company_id::text,
    'deleted_rows=' || v_total::text || '; new_year=' || v_year::text
  );
  return jsonb_build_object(
    'deleted_rows', v_total,
    'new_financial_year', v_year,
    'new_financial_year_id', v_year_id,
    'tables', v_counts
  );
end $$;

revoke all on function public.admin_reset_company_data_v18(uuid) from public, anon;
grant execute on function public.admin_reset_company_data_v18(uuid) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 9) تحقق سريع بعد التنفيذ (اختياري للقراءة فقط)
-- ---------------------------------------------------------------------------
-- select count(*) as items from public.items;
-- select count(*) as trips_without_item from public.invoice_trips where item_id is null;
