-- ============================================================================
-- تشديد أمان قاعدة بيانات قائمة (يعمل فوق schema.sql أو migration_auth_vat.sql)
-- الصق هذا الملف كاملاً في Supabase Dashboard > SQL Editor > Run (آمن التكرار)
--
-- يعالج:
--  1) منع المستخدم من تعديل role/is_active في ملفه (تقييد أعمدة + دوال مطوّر)
--  2) فرض البريد والدور من JWT (منع تزوير الملف الشخصي)
--  3) إلغاء امتيازات anon على الجداول (أقل امتياز)
--  4) تقييد search_path في دوال SECURITY DEFINER
--  5) إضافة سجل نشاط (audit log) ودوال حذف الشركة
-- ============================================================================

-- ---------------------------------------------------------------------------
-- سجل النشاط
-- ---------------------------------------------------------------------------
create table if not exists public.activity_logs (
  id          bigint generated by default as identity primary key,
  actor_id    uuid references auth.users(id) on delete set null,
  actor_email text default '',
  action      text not null,
  entity      text default '',
  entity_id   text default '',
  detail      text default '',
  created_at  timestamptz default now()
);
create index if not exists idx_logs_created on public.activity_logs(created_at);

create or replace function public.log_activity(
  p_action text, p_entity text default '', p_entity_id text default '', p_detail text default ''
) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into public.activity_logs (actor_id, actor_email, action, entity, entity_id, detail)
  values (auth.uid(), coalesce(auth.jwt() ->> 'email', ''), p_action, p_entity, p_entity_id, p_detail);
end $$;

alter table public.activity_logs enable row level security;
drop policy if exists activity_read on public.activity_logs;
create policy activity_read on public.activity_logs for select
  using (actor_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
-- إعادة تعريف is_active_user مع search_path مُقيّد
-- ---------------------------------------------------------------------------
create or replace function public.is_active_user() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select p.is_active from public.profiles p where p.id = auth.uid()),
    true
  );
$$;

-- ---------------------------------------------------------------------------
-- استبدال حارس الملف الشخصي القديم (set_admin_role) بالنسخة الأمنية
-- ---------------------------------------------------------------------------
create or replace function public.set_profile_guard() returns trigger
language plpgsql as $$
declare
  v_email text;
begin
  v_email := coalesce(auth.jwt() ->> 'email', new.email);
  new.email := v_email;
  if v_email = 'conta.moha@gmail.com' then
    new.role := 'admin';
  else
    new.role := 'user';
  end if;
  new.is_active := coalesce(new.is_active, true);
  return new;
end $$;

drop trigger if exists trg_profiles_guard on public.profiles;
create trigger trg_profiles_guard
  before insert on public.profiles
  for each row execute function public.set_profile_guard();

drop trigger if exists trg_profiles_admin on public.profiles;
drop function if exists public.set_admin_role();

create or replace function public.trg_profile_signup() returns trigger
language plpgsql as $$
begin
  perform public.log_activity('signup', 'profile', new.id::text, new.company_name);
  return new;
end $$;

drop trigger if exists trg_profiles_signup on public.profiles;
create trigger trg_profiles_signup
  after insert on public.profiles
  for each row execute function public.trg_profile_signup();

-- ---------------------------------------------------------------------------
-- إعادة بناء سياسات الملف الشخصي (فصل القراءة/الإدراج/التعديل — منع الحذف الذاتي)
-- ---------------------------------------------------------------------------
drop policy if exists profiles_own on public.profiles;
drop policy if exists profiles_admin on public.profiles;
create policy profiles_own_select on public.profiles for select using (id = auth.uid());
create policy profiles_own_insert on public.profiles for insert
  with check (id = auth.uid() and company_id is null);
create policy profiles_own_update on public.profiles for update
  using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_admin on public.profiles for all
  using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- دوال إدارة المطوّر
-- ---------------------------------------------------------------------------
create or replace function public.admin_set_profile_status(p_id uuid, p_active boolean) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  update public.profiles set is_active = p_active where id = p_id;
  perform public.log_activity(
    case when p_active then 'admin.activate' else 'admin.deactivate' end,
    'profile', p_id::text, '');
end $$;

create or replace function public.admin_set_profile_role(p_id uuid, p_role text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  if p_role not in ('user', 'admin') then raise exception 'دور غير صالح.'; end if;
  update public.profiles set role = p_role where id = p_id;
  perform public.log_activity('admin.set_role', 'profile', p_id::text, p_role);
end $$;

create or replace function public.admin_delete_company(p_id uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'غير مصرح لك بهذا الإجراء.'; end if;
  delete from public.advance_settlements where user_id = p_id;
  delete from public.payrolls             where user_id = p_id;
  delete from public.payment_vouchers     where user_id = p_id;
  delete from public.receipt_vouchers     where user_id = p_id;
  delete from public.trip_expenses        where user_id = p_id;
  delete from public.invoice_trips        where user_id = p_id;
  delete from public.invoices             where user_id = p_id;
  delete from public.banks                where user_id = p_id;
  delete from public.cashboxes            where user_id = p_id;
  delete from public.vehicles             where user_id = p_id;
  delete from public.employees            where user_id = p_id;
  delete from public.customers            where user_id = p_id;
  delete from public.year_snapshots       where user_id = p_id;
  delete from public.financial_years      where user_id = p_id;
  delete from public.settings             where user_id = p_id;
  delete from public.profiles             where id = p_id;
  perform public.log_activity('admin.delete_company', 'profile', p_id::text, '');
end $$;

-- ---------------------------------------------------------------------------
-- أقل امتياز: إلغاء وصول anon وإعادة المنح الضيقة + تقييد أعمدة الملف الشخصي
-- ---------------------------------------------------------------------------
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

revoke update on public.profiles from authenticated;
grant update (name, company_name, phone) on public.profiles to authenticated;

revoke execute on function public.admin_set_profile_status(uuid, boolean) from public, anon;
revoke execute on function public.admin_set_profile_role(uuid, text) from public, anon;
revoke execute on function public.admin_delete_company(uuid) from public, anon;
grant execute on function public.admin_set_profile_status(uuid, boolean) to authenticated, service_role;
grant execute on function public.admin_set_profile_role(uuid, text) to authenticated, service_role;
grant execute on function public.admin_delete_company(uuid) to authenticated, service_role;
